name: Newfangled Me
markdown: redcarpet
pygments: true
permalink: /:title
exclude: [Gemfile, Gemfile.lock]
include: [images]
sass:
    syntax: scss        # scss|sass
    style:  compact  # nested|expanded|compact|compressed